const useModule = require('./code')
const fs = require('fs')
const path = require('path')
console.log(fs)
fs.mkdir('./move/',()=> {console.log('hello')})
const file = fs.readFileSync('./README.md', {encoding: 'utf-8'}).toString().toUpperCase()
fs.writeFileSync('./lib.js', "var me = True; const wish = 1")
console.log(file)
// fs.appendFileSync('./lib.js', " testing this out too")
path.join('./move/hello.js')